TClark1011/bag-of-holding

.gitignore
jest.config.js
jest.setup.ts
package.json
tests/backend/db.test.ts
tests/db.test.ts
tests/frontend/homePage.spec.tsx
tests/frontend/sheetPage.spec.tsx

Db testing

---

README.md

changed .env.local to .env

---

db/dbReducer.ts
package.json
state/inventoryReducer.ts
tests/frontend/inventoryState.test.ts
types/InventorySheetState.ts
yarn.lock

Fixed action type inference in `inventoryReducer`.
Refactored `dbReducer` to use a switch statement.
Wrote tests for `inventoryReducer`.
Resolves #31

Reducer refactor

---

package.json

Setup a script that will run after the `yarn install` (or just `yarn`) to set up husky

fix(workspace): :wrench: setup post install hook to run husky

---

jest.config.js
package.json

tests can now be easily executed with a single command, with the output of all tests appearing in a single combined output

test(workspace): :wrench: implemented jest tests

---

.vscode/settings.json
package.json
src/db/connectToMongoose.ts
tests/backend/db.test.ts
yarn.lock

implemented 'mock-mongoose' 
Resolves #38

Mock mongoose

---

.husky/commit-msg
commitlint.config.js
package.json
yarn.lock

Commitlint

---

CHANGELOG.md
CHANGELOG_public.md
README.md
package.json
yarn.lock

Implemented `commitizen` as well as `standard-version`.
Created corresponding documentation.
Resolves #34

Commitizen

---

scripts/fixLegacyMembers.ts

A script that updates sheets to use the new members data type

Fix sheets script

---

src/components/domain/SheetPage/Dialogs/WelcomeDialog.tsx

issue-22: "If you lose the URL to a sheet..." in the WelcomeDialog.tsx

fix(scripts): fix grammar in welcome dialog

---

scripts/fixLegacyMembers.ts
src/components/domain/SheetPage/Dialogs/SheetOptionsDialog.tsx
src/components/ui/PartyMemberData.tsx
src/db/dbReducer.ts
src/state/inventoryReducer.ts
src/state/sheetPageState.ts
src/types/InventorySheetState.ts
src/utils/findItemWithId.ts
tests/backend/db.test.ts
tests/fixtures/itemFixtures.ts
tests/fixtures/membersFixtures.ts
tests/frontend/inventoryState.test.ts
tests/frontend/page_specs/sheetPage.spec.tsx

Handle updates to member objects

Member updates

---

src/pages/sheets/[sheetId].tsx

Resolves #1 [sheetid].tsx sheetOptions IconButton add DarkMode

fix(frontend): update sheet options color mode

---

.github/workflows/test.yaml
package.json
src/db/connectToMongoose.ts
tests/backend/db.test.ts
yarn.lock

This branch exists only for debugging errors that are occurring with auto testing via github actions

GitHub actions testing debugging

---

.vscode/settings.json
next.config.js
src/components/domain/GetStartedButton.tsx
src/config/publicEnv.ts

Implemented maintenance mode
Resolves #60

Maintenance mode

---

src/components/templates/View.tsx
src/pages/sheets/[sheetId].tsx

Removed opinionates styling from `View` component and implemented `View` component into `[sheetId]` file

View styling

---

src/components/domain/TopNav.tsx
src/constants/branding.ts
src/pages/info.tsx

added link to subreddit
Resolves #66

Reddit link

---

package.json
scripts/migrateToOnePointOne.js
src/config/env.ts
src/db/SheetModel.ts
yarn.lock

Migration script

---

src/components/domain/SheetPage/MemberTotalsTable.tsx
src/pages/sheets/[sheetId].tsx
tests/frontend/page_specs/sheetPage.spec.tsx

Resolves #84; renamed MemberCarryWeightTable to MemberTotalsTable in 3 files

refactor(fullstack): renamed MemberCarryWeightTable to MemberTotalsTable

---

CHANGELOG.md
package.json

chore(workspace): :bookmark: fixed version number

---

.github/workflows/release.yaml

ci(workspace): 🎡 run release script when a PR merges to main

---

next-env.d.ts
package.json
src/components/domain/SheetPage/Dialogs/SheetOptionsDialog.tsx
src/components/ui/ColorModeSwitch.tsx
src/config/theme.ts
src/pages/_app.tsx
src/pages/sheets/[sheetId].tsx
tsconfig.json
yarn.lock

color mode flashing has been greatly reduced (possibly fully fixed, need to see how it works on the preview build on Vercel). Upgraded next, chakra and emotion dependencies.
✅ Closes: #127

fix(frontend): 🐛 fixed (or at least improved) color mode flash

---

src/features/sheets/validation/itemValidation.ts

description increased from 400 to 4000, reference increased from 100 to
200

feat(frontend): 🎸 increase description, reference field limits
